# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8eee7fed7b2f53fa06c17cb671a74b4e81390d60feae50c5b44ff385ebb268ea0667bdbd5cc4f174be9d227dc318e5188be67f1644681bc1dc7dfb203b88a7b6

test:
  secret_key_base: fca60824e0538cf844b99a3762a1d7ea70a6e3a0d3cacf54b15b2c441f81bc7b2ad9515bdeace79c40ef923b32d7cd96f665a2cca33fe1489aa9d05de07ded41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
